### ISSUE TITLE
Issues for Moz Class - GitHub (Day 1)

### ISSUE THREAD

**Issue by dominicpagano1** [mozilla/web-lit-training#24]
Not entirely sure how the GitHub will help me in the real world.  Probably cause I have no idea what I'm doing but maybe some real world experiences and examples of how GitHub works in a workplace environment would help.

**Comment by stephwright** [comment]
We're going to be going more deeply into GitHub and what you can do with it today.  Hopefully this will give you a few more ideas on how it can be used.
