### ISSUE TITLE
Recipe Swap

### ISSUE THREAD

**Issue by Korilin25** [mozilla/web-lit-training#33]
The recipe trading was extremely uncomfortable. It's really tough exercise for people with social anxiety issues. Other than that exercise.. class has been great and very informative.

**Comment by stephwright** [comment]
Thank you, @Korilin25 ... We absolutely try to be as inclusive as possible for all folks with varying comfort levels.  We will be clear next time that it is not necessary for everyone to get up and swap recipes if they don't feel comfortable doing so.
