### ISSUE TITLE
Suggestion for the GitHub lesson

### ISSUE THREAD

**Issue by aldo1973** [mozilla/web-lit-training#37]
more exercise and slow down so others can catch up.

**Comment by stephwright** [comment]
Thanks @aldo1973 !!  When you say "more exercise" are you talking about workshop exercises or "more exercise" like the stand-up and shake exercise we did at the end.

**Comment by aldo1973** [comment]
Both

Sent from my iPhone

On Aug 5, 2016, at 16:38, Stephanie Wright <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks @aldo1973https://github.com/aldo1973 !! When you say "more exercise" are you talking about workshop exercises or "more exercise" like the stand-up and shake exercise we did at the end.

##
