### ISSUE TITLE
Suggestion to improve cheatsheet

### ISSUE THREAD

**Issue by Eodbell88** [mozilla/web-lit-training#41]
The markdown cheat sheet was not the easiest to follow along with, especially for beginners. The markdown cheat sheet was crammed together, it may help to break it down a little more to make it less confusing. The bold and italic references were a little confusing, it took a good amount to decipher the information through trial and error.

**Comment by stephwright** [comment]
We've had a couple suggestions for a paper one to have at the table, as well... what do you think?
