### ISSUE TITLE
Register for account as first step

### ISSUE THREAD

**Issue by Codestar71** [mozilla/web-lit-training#45]
it seems the class lost it's way when certain members were not able to create a github account because they could not verify their email account.
I recommend RP6 instruct the students to prepare their email ahead of time to ensure they can verify their account.
Students should know they must register for Mozilla and Github ahead of time. 
Recommend posting the entire agenda ahead of time as well.

Overall, great training.

**Comment by stephwright** [comment]
Great recommendation @Codestar71 and totally agree that we lost momentum with the GitHub account creation.  Will definitely be incorporating this feedback for next time.
