### ISSUE TITLE
Suggestion: for improvement in class

### ISSUE THREAD

**Issue by JaThomas13** [mozilla/web-lit-training#46]
1.  I would like to have a little more one-on-one.
2.  I like the class, and its administrators, although, I do feel
    that there may be a need for more administrators.
3.   I realize that being unfamiliar with things is sometimes difficult
     to understand, but believe I will survive.

**Comment by stephwright** [comment]
I love your positivity @JaThomas13 !!!  Thanks for the constructive feedback! 👍
