### ISSUE TITLE
Add a cheat sheet to "Military Excuse generator"

### ISSUE THREAD

**Issue by Bhettiger** [mozilla/web-lit-training#48]
Something that helps me with coding is having an example of codes on a side bar of some sort, so you can see all the different codes you can experiment with. For example I had an other browser open to "http://www.w3schools.com/tags/ref_colornames.asp" and it showed me different HTML codes I could throw into the script.

**Comment by stephwright** [comment]
Thanks for the recommendation and for the resource!  I suspect it would have been helpful to have the markdown cheatsheet for the GitHub lesson, too.
