### ISSUE TITLE
Add Cheatsheet of commands for "Thimble".

### ISSUE THREAD

**Issue by JUmbrella** [mozilla/web-lit-training#49]
Hello,

I honestly have to say thank you for the opportunity that you guys have provided to us, I just had to say that. Now to the issue I have notice, please correct me if I am wrong, but I don't think that there is a way to link **Thimble & GitHub** together to make a web page, clam domain and publish it out to the public as personal or business. Also what can I do to avoid **Copy Right Violations**?

**Comment by stephwright** [comment]
I know this doesn't address the question re: Thimble & GitHub (I don't know of a way to combine those) but regarding copyright, this is a great resource: https://www.ocps.net/lc/east/htc/mediacenter/Documents/FairUse.pdf
